### ISSUE TITLE
Build script for XrayKit.xcframework

### ISSUE THREAD

**Issue by vanyasem** [arror/Tun2SocksKit#15]
Is there a build script to build `XrayKit.xcframework` manually?

**Comment by vanyasem** [comment]
I am talking about:
```
      - uses: actions/checkout@v3
        with:
          repository: ${{secrets.RESPOSITORY}}
          token: ${{secrets.PAT}}
          path: 'xray'
```

What is the `secrets.RESPOSITORY`? Is it available?
