### ISSUE TITLE
无法代理成功

### ISSUE THREAD

**Issue by whatbugsyou** [arror/Tun2SocksKit#7]
networkSettings 配置：
```swift
        let networkSettings = NEPacketTunnelNetworkSettings(tunnelRemoteAddress: "254.1.1.1")
        networkSettings.mtu = 9000
        let ipv4Settings = NEIPv4Settings(addresses: ["198.18.0.1"], subnetMasks: ["255.255.0.0"])
        ipv4Settings.includedRoutes = [.default()]
        networkSettings.ipv6Settings = nil
        networkSettings.dnsSettings = NEDNSSettings(servers: ["8.8.8.8"])
        networkSettings.ipv4Settings = ipv4Settings
```
tunnel配置
```yml
let config = """
        tunnel:
          mtu: 9000
        socks5:
          port: 10808
          address: 121.232.124.241
          udp: 'udp'
          username: 'xxxxxx'
          password: 'xxxxxx'
        """
```

开启VPN后，通过域名访问不了网站。直接通过ip访问可以成功，并且在socks5服务端 `121.232.124.241`上确认是走的此代理。

xcode中的检控显示：
<img width="1323" alt="image" src="https://github.com/arror/Tun2SocksKit/assets/49427907/c986ccfb-6006-4d40-8674-c6c425c28355">
